### ISSUE TITLE
Design for removing game

### ISSUE THREAD

**Issue by apulverizer** [apulverizer/klask-app#29]
@dawitelias I think we should add a menu item when we implement that menu for the profile games. On this menu we should have 5 options (Delete Game, View Profile, Challenge, You Won, You Lost).

What should be the workflow when a user clicks "Delete Game"?
Do we show a confirmation dialog with similar style to the score-card?

**Comment by dawitelias** [comment]
The design for this is in Figma. Basically, once you tap the user row in your Profile games played list, we show a similar (but slightly modified) menu with a `DELETE GAME` action.

![deletegame](https://user-images.githubusercontent.com/7459713/38472339-8c1509a2-3b4c-11e8-96b8-ef7102ec5c1e.png)

Tapping `DELETE GAME` will simply delete the game and remove the row from the games played list.
