### ISSUE TITLE
Arena Switcher 

### ISSUE THREAD

**Issue by apulverizer** [apulverizer/klask-app#5]
How do I switch the arena? Should we put a button on the standings/profile header?

**Comment by dawitelias** [comment]
@apulverizer Adding this for posterity. 

"Change arenas" option added to the profile overflow menu. We just have to ensure this functionality also exists on the profile screen.

**Comment by apulverizer** [comment]
Will re-route to arenas route to choose arena after clicking button in profile-overflow
